{{- $env := .Values.env -}}
{{- range $component, $image := .Values.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alerthawk.fullname" $ }}-{{ $component }}
  labels:
    app: {{ include "alerthawk.name" $ }}
    component: {{ $component }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "alerthawk.name" $ }}
      component: {{ $component }}
  template:
    metadata:
      labels:
        app: {{ include "alerthawk.name" $ }}
        component: {{ $component }}
    spec:
      containers:
        - name: {{ $component }}
          image: {{ $image }}
          ports:
            - containerPort: {{ $.Values.service.port }}
          env:
            {{- if ne $component "ui" }}
            - name: ASPNETCORE_ENVIRONMENT
              value: {{ $env.ASPNETCORE_ENVIRONMENT }}
            - name: ConnectionStrings__SqlConnectionString
              value: {{ $env.ConnectionStrings__SqlConnectionString }}
            {{- end }}
---
{{- end }}
