{{- range $component, $image := .Values.image }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" $ }}-{{ $component }}
  labels:
    app: {{ include "name" $ }}
    component: {{ $component }}
spec:
  replicas: {{ (index $.Values $component).replicas | default $.Values.defaultReplicas }}
  selector:
    matchLabels:
      app: {{ include "name" $ }}
      component: {{ $component }}
  template:
    metadata:
      labels:
        app: {{ include "name" $ }}
        component: {{ $component }}
    spec:
      containers:
        - name: {{ $component }}
          image: {{ $image }}
          ports:
            - containerPort: {{ $.Values.service.port }}
          env:
            {{- with (index $.Values $component).env }}
            {{- range $key, $value := . }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
---
{{- end }}
