{{- range $component, $image := .Values.image }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fullname" $ }}-{{ $component }}
  labels:
    app: {{ include "name" $ }}
    component: {{ $component }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: {{ $.Values.service.port }}
  selector:
    app: {{ include "name" $ }}
    component: {{ $component }}
---
{{- end }}
