apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}.{{ .Values.appName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      {{- if eq .Values.appName "ui" }}
      port: {{ .Values.service.uiPort }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}.{{ .Values.appName }}
