{{- if and .Values.serviceAccount.create .Values.serviceAccount.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.serviceAccount.name }}-{{ .Values.serviceAccount.clusterRoleBinding.clusterRole | default "cluster-admin" | replace ":" "-" | replace "." "-" }}
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.clusterRoleBinding.clusterRole | default "cluster-admin" }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}

