{{- if and .Values.serviceAccount.create .Values.serviceAccount.clusterRoleBinding.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.serviceAccount.clusterRoleBinding.clusterRoleName | default "alerthawk-metrics-collector" }}
  labels:
    {{- include "labels" . | nindent 4 }}
rules:
  # Core API – events (namespaced)
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "get"]
  # Core API – nodes (cluster-scoped)
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["list", "get"]
  # Core API – node proxy (PVC/stats summary)
  - apiGroups: [""]
    resources: ["nodes/proxy"]
    verbs: ["get"]
  # Core API – pods (namespaced)
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list", "get"]
  # Core API – pod logs (when COLLECT_LOGS=true)
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
  # Metrics API – node and pod metrics
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["list", "get"]
  # Version endpoint (for GetVersionAsync / cloud detection)
  - nonResourceURLs: ["/version"]
    verbs: ["get"]
{{- end }}
