nameOverride: ""

image:
  monitoring: thiagoguaru/alerthawk.monitoring:3.1.23

monitoring:
  replicas: 1
  env:
    ASPNETCORE_ENVIRONMENT: Development
    ConnectionStrings__SqlConnectionString: your-connection-string
    RabbitMq__Host: rabbitmq-host
    RabbitMq__User: rabbitmq-user
    RabbitMq__Pass: rabbitmq-pass
    Sentry__Enabled: false
    Sentry__Dsn: sentry-dsn-url
    Sentry__Environment: Local
    SwaggerUICredentials__username: admin
    SwaggerUICredentials__password: admin
    CacheSettings__CacheProvider: Redis
    CacheSettings__RedisConnectionString: redis-connection-string
    AzureAd__ClientId: clientid
    AzureAd__TenantId: tenantid
    AzureAd__ClientSecret: secret
    AzureAd__Instance: instance
    azure_blob_storage_connection_string: azure-blob-storage-connection-string
    azure_blob_storage_container_name: azure-blob-storage-container-name
    Jwt__Key: jwt-key
    Jwt__Issuers: issuers
    Jwt__Audiences: audiences
    AUTH_API_URL: specify-auth-url-address
    CACHE_PARALLEL_TASKS: 10
    ipgeo_apikey: ipgeo-api-key
    enable_location_api: false
    enable_screenshot: false
    screenshot_wait_time_ms: 2000
    enable_screenshot_storage_account: false
    Logging__LogLevel__Default: Warning
    Logging__LogLevel__Microsoft.IdentityModel.LoggingExtensions.IdentityLoggerAdapter: Critical
    Downsampling__Active: true
    Downsampling__IntervalInSeconds: 60
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: false
    CHECK_MONITOR_AFTER_CREATION: true
    QueueType: RABBITMQ
    ServiceBus__ConnectionString: your-sb-connstring
    ServiceBus__QueueName: notifications
    DISABLE_MASTER: true
    monitor_region: 7
